[#automatic-image-build]
= Automatic Image Build

With the build context and the image specified in `docker-compose.yaml`, Docker will automatically build the image. 

For that the image name needs to be added to the `.env` file at the same level as your new `hello-world.docker-compose.yaml`. Create the file, if it doesn't exists yet and add the following lines:

[source,env]
----
HELLO_WORLD_SVC=${DOCKER_REPO}/hello-world-svc:main-native
HELLO_WORLD_BFF=${DOCKER_REPO}/hello-world-bff:main-native
HELLO_WORLD_UI=${DOCKER_REPO}/hello-world-ui:main
----

Now you can import the initial data by running:

[source,sh]
----
./import-onecx.sh
----

Now the application needs to be built with `npm run build` and the onecx-local-env can be started with:

[source,sh]
----
docker compose -f hello-world.docker-compose.yml --profile base up -d
----

NOTE: To ensure the application runs correctly, make sure to add entries for `hello-world-bff` and `hello-world-svc` to your system's hosts file (e.g., `C:\Windows\System32\drivers\etc\hosts` on Windows).

For more details on these commands and necessary configurations, refer to the link:https://onecx.github.io/docs/onecx-local-env/current/general/index.html[onecx-local-env documentation].

Now the application should be accessible under `http://local-proxy/mfe/helloWorld/hello` in the OneCX Shell.

*This method of running the application may lead to potential caching issues that could prevent changes from being reflected immediately.*