[#testing-changes-to-existing-onecx-core-apps]
= Testing Changes to Existing OneCX Core Apps

If you have made changes to an existing OneCX core app (e.g., OneCX Theme UI) it can be tested the same way as for custom applications.
Build the app locally and follow the xref:manual-image-build[manual image build process] above. Replace the image reference in `docker-compose.yaml` with your locally built image, start the environment and verify your changes in the OneCX Shell.

If you need to do changes in `shell-ui` and want to test your changes in the `onecx-local-env`, you can edit the `docker-compose.yaml` in your local environment and update the `onecx-shell-ui` service as follows:

[source,yaml]
----
onecx-shell-ui:
    # image: localhost/onecx-shell-ui:latest
    build:
        context: /path/to/onecx-shell-ui
        dockerfile: Dockerfile
----

With this configuration, Docker Compose will build the image from your local source. To build (or rebuild) the image and start the service, run:

[source,sh]
----
docker compose --profile base up -d
----

Now you can build the shell locally with `npm run build`, then rebuild the Docker image, and test your changes within the local environment.