[#manual-image-build]
= Manual Image Build

To avoid caching issues and ensure the latest code is always used, it is recommended to manually build the Docker image after building your app locally.

First, go to your application and *remove the cache and dist folder to avoid using cached images*:

[source,sh]
----
rm -rf .nx/cache ./dist
----

Then you can build your application and create a local docker image:

[source,sh]
----
npm run build
docker build --no-cache -t helloworld_local .
----

Now in the `onecx-local-env` navigate to the .env file at the same level as your `hello-world.docker-compose.yaml`. The image name for `HELLO_WORLD_UI` should match the name you used when building the local docker image in your application.

[source,env]
----
HELLO_WORLD_SVC=${DOCKER_REPO}/hello-world-svc:main-native
HELLO_WORLD_BFF=${DOCKER_REPO}/hello-world-bff:main-native
HELLO_WORLD_UI=helloworld_local:latest
----

Now you can also import the initial data by running:

[source,sh]
----
./import-onecx.sh
----

and start the service with:

[source,sh]
----
docker compose -f hello-world.docker-compose.yaml --profile base up -d
----

Now the local image is used and changes in the application should be reflected under `http://local-proxy/onecx-shell/admin/helloWorld/hello` after rebuilding the image of the application with `docker build --no-cache -t helloworld_local .`.

If you want to your application to reflect changes immediately without rebuilding the image each time, you can set up your application for hot reloading by following these steps in the xref:enable_hot_reload[Enable Hot Reload] section.