[#automatic-image-build]
= Automatic Image Build

If you want to develop or test local changes, you can use Docker's build context to build the image from your local source code each time you run `docker compose`. With the build context from your local application, Docker will automatically build the image.

To use this approach, first update your `hello-world.docker-compose.yaml` to use a `build` section instead of an image reference. Adjust the `context` to your local app path and reference the application's Dockerfile as shown in the example below:

[source,yaml]
----
include:
  - docker-compose.yaml
services:
  hello-world-ui:
    # image: ${HELLO_WORLD_UI}
    build:
      context: /path/to/hello-world-ui
      dockerfile: Dockerfile
    environment:
      APP_BASE_HREF: /mfe/helloWorld/
      APP_ID: hello-world-ui
      PRODUCT_NAME: hello-world
    depends_on:
      hello-world-bff:
        condition: service_healthy
    labels:
      - traefik.http.services.hello-world-ui.loadbalancer.server.port=8080
      - traefik.http.routers.hello-world-ui.rule=Host(`local-proxy`)&&PathPrefix(`/mfe/helloWorld/`)
    networks:
      - default
    profiles:
      - base
      - hello-world
      - hello-world-ui
      - all
----

Now you can import the initial data in the `onecx-local-env` by running:

[source,sh]
----
./import-onecx.sh
----

The application needs to be built with `npm run build` and the `onecx-local-env` can be started with:

[source,sh]
----
docker compose -f hello-world.docker-compose.yaml --profile base up -d
----

Your application will now be built and available at `http://local-proxy/onecx-shell/admin/helloWorld/hello` in the OneCX Shell. If you make changes in your application, you need to rebuild it with `npm run build` and restart the `onecx-local-env` with the command above.

*This method of running the application may lead to potential caching issues that could prevent changes from being reflected immediately.* In case of such issues, you can rebuild the UI with `npm run build` and then run `docker compose build && docker compose -f hello-world.docker-compose.yaml --profile base up -d`. You can check in the logs of the `hello-world-ui` container if the new build was used by running `docker logs hello-world-ui`.