= Creating a new OneCX Angular App

[#general-overview]
== General Overview

//TODO: add link to onecx env setup guide
After setting up the onecx-environment locally, you can begin creating your own application within this environment. This guide walks through the process of building a simple "Hello World" Angular app and integrating it into the OneCX environment.
To integrate an application into the OneCX environment, it should follow the standard architecture consisting of three main services (ui, bff and svc).
These services are consumed by the OneCX shell, which orchestrates and displays the UI components within the broader platform.

[#creating-the-ui]
== Creating the UI

[#creating-basic-ui-structure]
=== 1. Create the basic UI structure

We start with creating the UI structure of our "Hello World" App by running the following commands using the custom OneCX generator.

Please check the link:https://onecx.github.io/docs/nx-plugins/current/general/getting_started/prerequisites.html[prerequisites for using the generator] before starting.

==== Setup New Angular Workspace

First, we can generate the basic project structure and required files for the application.
This includes necessary configuration and build files, initial Angular source code, generated API services, translation assets, Swagger specifications, environment settings and Helm deployment configurations.

We can set up the new Angular workspace by running:

[source,sh]
----
npx @onecx/create-workspace ngrx hello-world
----
NOTE: Details to generating a new OneCX Angular workspace can be found link:https://onecx.github.io/docs/nx-plugins/current/general/getting_started/new-onecx-app.html[here].

Navigate into the newly created hello-world directory and install the packages with `npm install`. 

==== Add a Feature Module

Now we want to add a feature module to our application, that encapsulates the functionality of our new hello-world feature. Therefore a new folder with the name of the feature module will be created in the `/src/app/` directory.

This will be generated by running the following command:

[source,sh]
----
nx generate @onecx/nx-plugin:feature hello-world
----
NOTE: Details to generating a feature module can be found link:https://onecx.github.io/docs/nx-plugins/current/general/getting_started/feature-module.html[here].

==== Add a Search Page

Additionally we can add a search feature, that includes a table and allows users to search for an item in a certain column.
The search page can be generated in the same way as the feature module:

[source,sh]
----
nx generate @onecx/nx-plugin:search hello-world
----
NOTE: Details to generating a search page can be found link:https://onecx.github.io/docs/nx-plugins/current/general/getting_started/search-page.html[here].

==== Add a Details Page

Now we can also create a details page for the items in the search results by running:

[source,sh]
----
nx generate @onecx/nx-plugin:details hello-world
----
NOTE: Details to generating a details page can be found link:https://onecx.github.io/docs/nx-plugins/current/general/getting_started/details-page.html[here].

The application can now be built, tested and started by running `npm run build`, `npm run test` and `npm start`.

For further customization of the app, you can refer to the general link:https://onecx.github.io/docs/[OneCX generator documentation].

[#include-application-in-onecx-environment]
=== 2. Include application in OneCX environment

Now let's integrate the Hello-world app into the OneCX environment using the onecx-local-env. *This section assumes your local environment is already set up and running*.

[#synchronization]
==== Synchronization

In your hello-world UI folder, sync the app with your local environment (adjust the path to your `onecx-local-env`):

[source,sh]
----
npx @onecx/local-env-cli sync -e /path/to/onecx-local-env ui hello-world /hello-world ./helm/values.yaml
----

In this command:

- `hello-world` refers to the product name,
- `/hello-world` specifies the product's base path,
- `./helm/values.yaml` is the path to the application's `values.yaml` file, that was generated by the OneCX generator

This command will adjust the files in your onecx-local-env to include the necessary information about the new application.

[#adding-to-docker-compose]
==== Add the UI to Docker Compose

Add the UI as an image to the `docker-compose.yaml` of your `onecx-local-env`:

[source,sh]
----
npx @onecx/local-env-cli docker -e /path/to/onecx-local-env -s ui name create hello-world /mfe/helloWorld/
----

Now the name.docker-compose.yaml should contain an image for `hello-world-ui`.

NOTE: More details to the onecx-local-env-cli can be found link:https://github.com/onecx/onecx-local-env-cli/[here].

[#start-environment]
==== Start the Environment and Import Data

Now all services can be started with running the following command:

[source,sh]
----
docker compose --profile all up -d
----

Then the data can be imported:

[source,sh]
----
bash import-onecx.sh
----

Your `hello-world` app should now be visible under `http://local-proxy/onecx-shell/admin/hello-world`.

[#creating-the-bff]
== Creating the BFF

[#creating-the-svc]
== Creating the SVC

