= Creating a new OneCX Angular App

== General Overview

After setting up the onecx-environment locally, you can begin creating your own application within this environment. This guide walks through the process of building a simple "Hello World" Angular app and integrating it into the OneCX environment.
To integrate an application into the OneCX environment, it should follow the standard architecture consisting of three main services (ui, bff and svc).
These services are consumed by the OneCX shell, which orchestrates and displays the UI components within the broader platform.

== Creating the UI

*1 Create the basic UI structure*

We start with creating the UI structure of our "Hello World" App by running the following commands using the custom OneCX generator.

* Please check the link:https://onecx.github.io/docs/nx-plugins/current/general/getting_started/prerequisites.html[prerequisites for using the generator] before starting.

* First we are setting up a new Angular workspace by running:

[source,sh]
----
npx @onecx/create-workspace ngrx hello-world
----
NOTE: Details to generating a new OneCX Angular workspace can be found link:https://onecx.github.io/docs/nx-plugins/current/general/getting_started/new-onecx-app.html[here].

* Navigate into the newly created hello-world directory and install the packages with `npm install`. 
* Now a feature module can be generated by running the following command:

[source,sh]
----
nx generate @onecx/nx-plugin:feature hello-world
----
NOTE: Details to generating a feature module can be found link:https://onecx.github.io/docs/nx-plugins/current/general/getting_started/feature-module.html[here].

* In the same way we can generate a search feature for our module:

[source,sh]
----
nx generate @onecx/nx-plugin:search hello-world
----
NOTE: Details to generating a search page can be found link:https://onecx.github.io/docs/nx-plugins/current/general/getting_started/search-page.html[here].

* We can create a details page by running:

[source,sh]
----
nx generate @onecx/nx-plugin:details hello-world
----
NOTE: Details to generating a details page can be found link:https://onecx.github.io/docs/nx-plugins/current/general/getting_started/details-page.html[here].

The application can now be built, tested and started.

For further customization of the app, you can refer to the general link:https://onecx.github.io/docs/[OneCX generator documentation] or you can add for example a calendar or dropdown by following the instructions link:https://onecx.github.io/docs/guides/current/angular/ngrx/cookbook/adding-search-criteria/general.html[here].

*2 Include application in OneCX environment*

Now let's integrate the Hello-world app into the OneCX environment using the onecx-local-env. This section assumes your local environment is already set up and running.

**Synchronization**

In your hello-world UI folder, sync the app with your local environment (adjust the path to your `onecx-local-env`):

[source,sh]
----
npx @onecx/local-env-cli sync -e /path/to/onecx-local-env ui hello-world /hello-world ./helm/values.yaml
----

**Add the UI to Docker Compose**

Add the UI as an image to the `docker-compose.yaml` of your `onecx-local-env`:

[source,sh]
----
npx @onecx/local-env-cli docker --sections ui hello-world-ui create hello-world /mfe/hello-world/
----

This command will add an image for `hello-world-ui` to your Docker Compose setup.

NOTE: More details to the onecx-local-env-cli can be found link:https://github.com/onecx/onecx-local-env-cli/[here].

**Configure Imports**

* In `imports > product-store > microfrontends`, create a file named `hello-world_hello-world_ui.json` with the following content:

[source,json]
----
{
    "appVersion": "xxx",
    "appName": "hello-world-ui",
    "description": "Hello World UI",
    "remoteBaseUrl": "/mfe/hello-world/",
    "remoteEntry": "/mfe/hello-world/remoteEntry.js",
    "note": "Imported MFE",
    "exposedModule": "./HelloWorldModule",
    "technology": "WEBCOMPONENTMODULE",
    "remoteName": "hello-world",
    "tagName": "ocx-hello-world-component",
    "type": "MODULE",
    "deprecated": false,
    "undeployed": false
}
----

* In `imports > product-store > microservices`, create a file named `hello-world_hello-world_ui.json` with the following content:

[source,json]
----
{
    "version": "xxx",
    "description": "hello-world-ui",
    "name": "hello-world-ui",
    "type": "ui"
}
----

* In `imports > product-store >products`, create a file named `hello-world.json` with the following content:

[source,json]
----
{
    "version": "xxx",
    "description": "hello-world",
    "basePath": "/hello-world",
    "displayName": "hello-world",
    "iconName": "pi-briefcase"
    }
----

* In `imports > workspace`, open the file `onecx_admin.json` and add the following entry to the `products` array:

[source,json]
----
{
    "productName": "hello-world",
    "baseUrl": "/hello-world",
    "microfrontends": [
        {
            "appId": "hello-world-ui",
            "basePath": "/"
        }
    ]
},
----

**Start the Environment and Import Data**

* Now all services can be started with running the following command:

[source,sh]
----
docker compose --profile all up -d
----

* Then the data can be imported:

[source,sh]
----
bash import-onecx.sh
----

Your `hello-world` app should now be visible under `local-proxy/onecx-shell/admin/hello-world`.

== Creating the BFF


== Creating the SVC

